### PR TITLE
PG int2 requires Int16 to fit the full range

### PR DESCRIPTION
**Pull request by timmytofu**

### CODE REVIEW

**Comment by sdiehl** [comment]
All looks good to me. Thanks for catching this.

**Comment by sdiehl** [comment]
Out of curiosity, are you using this library?

**Comment by timmytofu** [comment]
Not yet, just discovered it and started playing around whilst unable to sleep last night. I'm interested, though. I've been passively working on a postgres library myself - just slightly more than `postgresql-simple` but still in that vain. No superfluous syntax, no tight coupling to the DB, queries written in SQL but pre-parsed, roughly checked for syntax, put in binary format, and semi-type safe arguments.

I'm trying to figure out how to do query building (the biggest thing missing from postgresql-simple)in a way that works with syntax checking and the semi type safety (if it executes without error once, it will execute without error every time until the DB schema changes). I don't want any ORM malarkey, I'd just like a bit of flexibility to build queries and offer some reasonable type safety while still offering the full surface area of postgres' functionality.

A bit of a ramble, but I'm always interested when I see mid-level libraries like this. I'd be interested in hearing about your intentions for this library - looks like you're focusing more on streaming than I might be - but feel free to msg me `timmy_tofu` on freenode or the same by email @linux.com if you're so inclined.

**Comment by sdiehl** [comment]
I basically wrote this library because the postgresql-simple libpq marshaling was particularly inefficient for certain composite structures (rows, vectors). So then I found the `postgresql-binary` library which was much more efficient and decided to rebase a postgresql-simple like API on top of it and it seems to yield like 10-15x improvement for large streaming cursor queries.

As far as my goals, long term I'd like to build a mid-level API on top for constructing queries in a type-safe way that was basically just idiomatic Haskell instead of having to go through source strings or TemplateHaskell. Opaleye get's pretty close ... don't know if you've looked at that approach yet but it's pretty nice although it's use of -XArrows is a little eccentric.

**Pull request merged**
